name: Doubting Nothing
favicon: null
layout_spectrum: 0.6668551277834922
typography_spectrum: 0.5522569459863007
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.1805391269735992
  lightness: 0.04894347907975316
  saturation: 0.34657847438938916
  rhythmicContrast: 0.7224144372157753
purpose: []
